services:

  visiotech.vineyardmanagementservice.api:
    image: ${DOCKER_REGISTRY-}visiotechvineyardmanagementserviceapi
    build:
      context: .
      dockerfile: src/Visiotech.VineyardManagementService.Api/Dockerfile
    depends_on:
      - sql-server

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: NuevaContra123#
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata: